openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: Word Count
    description: Endpoints for counting and analyzing words in a given text
paths:
  /api/word/top:
    post:
      tags:
        - Word Count
      summary: Get top N most frequent words
      description: Returns the top N most frequently occurring words in the provided text.
      operationId: topWords
      parameters:
        - name: limit
          in: query
          description: Maximum number of top words to return
          required: false
          schema:
            type: integer
            format: int32
            default: 5
          example: 5
      requestBody:
        description: Plain text to be analyzed
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: List of top N frequent words
          content:
            '*/*':
              schema:
                type: array
                example:
                  - key: the
                    value: 7
                  - key: dog
                    value: 3

  /api/word/frequency:
    post:
      tags:
        - Word Count
      summary: Get frequency of each word
      description: Returns a frequency map of words in the provided text.
      operationId: wordFrequency
      requestBody:
        description: Plain text to be analyzed
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: Map of word -> count
          content:
            '*/*':
              schema:
                type: string
                example:
                  the: 3
                  dog: 2

  /api/word/count:
    post:
      tags:
        - Word Count
      summary: Count total number of words
      description: Returns the number of words in the provided input text.
      operationId: countWords
      requestBody:
        description: Plain text to be analyzed
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: Number of words
          content:
            '*/*':
              schema:
                type: string
                example:
                  wordCount: 7

  /api/word/sample:
    get:
      tags:
        - Word Count
      summary: Get sample text
      description: Returns a sample English sentence for testing purposes.
      operationId: getSampleText
      responses:
        '200':
          description: Sample sentence
          content:
            '*/*':
              schema:
                type: string

  /api/word/help:
    get:
      tags:
        - Word Count
      summary: List help for all endpoints
      description: Returns descriptions of all available endpoints and their usage.
      operationId: getHelp
      responses:
        '200':
          description: Endpoint usage help
          content:
            '*/*':
              schema:
                type: string
                example:
                  POST /api/word/count: Returns total number of words in the input text.

components: {}
